### ISSUE TITLE
Compile failing on Raspberry Pi.

### ISSUE THREAD

**Issue by pnunn** [dnp3/opendnp3#105]
Hi there,

I'm trying to get the library to compile on a Raspberry Pi so that I can use the pi simulator (the pisimulator seems to have vanished off github in the last 2 days). 

Configure on the pi completes, but make fails with 

cpp/libs/openpal/src/openpal/logging/LogRoot.cpp: In constructor 'openpal::LogRoot::LogRoot(const openpal::LogRoot&, const char*)':
cpp/libs/openpal/src/openpal/logging/LogRoot.cpp:43:2: error: type 'openpal::LogRoot' is not a direct base of 'openpal::LogRoot'
Makefile:3867: recipe for target 'cpp/libs/openpal/src/openpal/logging/libopenpal_la-LogRoot.lo' failed

Any clues please?

Peter.

**Comment by jadamcrain** [comment]
Hi Peter,

Join the mailing list and re-post there please:

http://groups.google.com/group/automatak-dnp3

-Adam
