### ISSUE TITLE
Strange behaviour in asiopal::Synchronized under rare circumstances

### ISSUE THREAD

**Issue by atmurray** [dnp3/opendnp3#106]
Under rare situations WaitForValue() would return prior to condition.notify_all() being called in SetValue(). This results in ~Synchonized being called prior to the condition variable being notified resulting in erratic behaviour. Under linux this behaviour appears as deadlock, under Windows the application halts as Windows appears to detect some sort of deadlock.

I suspect the following occurs:
1. Parent (e.g. SynchronouslyGet) creates a Synchonized<> object 
2. Parent posts work on another thread that calls SetValue()
3. Parent calls WaitForValue()
4. SetValue() is called and obtains a lock on mutex
5. SetValue() sets isSet to true
6. SetValue() releases the lock on mutex (due to scoping)
7. WaitForValue() obtains a lock on mutex (either it was blocked or has just been called)
8. WaitForValue() skips to return value as isSet is true - skipping condition.wait()
9. The Synchronized object is cleaned up after it exits the scope of Parent
10. SetValue() attempts to call condition.notify_all() but condition is no longer a valid object?

We have mainly observed this when the stack has a significant (over 800) number of Outstations/Masters during:
- shutdown: possibly due to the synchonization of WaitForShutdown()?
- when asynchronously calling GetChannelStatistics(): which then calls SynchronouslyGet

Preparing pull request for 2.0.x that corrects this behaviour.

**Comment by jadamcrain** [comment]
Resolved in 659765e9870f17122e756.
