### ISSUE TITLE
Check why master is not confirming CROB

### ISSUE THREAD

**Issue by pgiu** [dnp3/opendnp3#108]
When sending commands to the RTU and we have a problem regarding the CROB command. We're sending a select before operate command, and the outstation is requesting a confirmation to the Select operation, but that confirmation never comes. Instead, the master performs an Operate Command.
More info and log file posted on: 
https://groups.google.com/d/topic/automatak-dnp3/uICtdU0piVI/discussion

**Comment by jadamcrain** [comment]
Resolved in 2.0.1-RC1
