### ISSUE TITLE
ControlStatus enum needs updated for new codes

### ISSUE THREAD

**Issue by damonsensus** [dnp3/opendnp3#115]
Based on the current DNP3 spec, the following codes need added to the ControlStatus enum:

10 AUTOMATION_INHIBIT
11 PROCESSING_LIMITED 
12 OUT_OF_RANGE 
13 DOWNSTREAM_LOCAL
14 ALREADY_COMPLETE
15 BLOCKED
16 CANCELLED
17 BLOCKED_OTHER_MASTER
18 DOWNSTREAM_FAIL

**Comment by jadamcrain** [comment]
Resolved in 2.0.1-RC1
