### ISSUE TITLE
ControlCode enum needs updated with PULSE_ON/PULSE_OFF values

### ISSUE THREAD

**Issue by damonsensus** [dnp3/opendnp3#116]
Based on the v2.04 version of the DNP3 spec, the following changes need to be implemented in the ControlCode enum:

PULSE should change to PULSE_ON (0x01)
PULSE_OFF (0x02) should be added.

*\* I know PULSE_OFF is often mocked and frequently not used, but it is defined and should probably be available in the API.

**Comment by jadamcrain** [comment]
LoL. Trust me there are worse things in the DNP3 spec, than pulse off.

**Comment by jadamcrain** [comment]
Resolved in 2.0.1-RC1
