### ISSUE TITLE
Link status listener interface

### ISSUE THREAD

**Issue by neilstephens** [dnp3/opendnp3#126]
It would be really nice to have an interface to be notified of a stack's link layer status, similar to how the channel state listener interface works.

I added a pull request as an easy way to share some prototype code for the feature. It's not intended to be actually merged in it's current state. Just to show what I mean and that it works. Sorry if that's not the done thing.

Cheers,
Neil.

**Comment by jadamcrain** [comment]
merged. Modified functionality to exist as sub-interface of IMasterApplication/IOutstationApplication
