### ISSUE TITLE
Quality of boolean values does not look compatible with some outstations

### ISSUE THREAD

**Issue by faburaya** [dnp3/opendnp3#13]
Hi, I have been implementing a dnp3 master using opendnp3.
For tests I use the slave simulator provided in https://github.com/gec/dnp3slavesim
The thing is, for binary points, the slave provides the quality value 0 for 'ONLINE', and opendnp3 cannot map that to the enumeration of binary quality when I read it from the Binary object. Is that correct?
Moreover, the quality retrieved from the same objects seems to be varying whenever I change the boolean value of the point. I believe this is not correct.

Kind regards, Felipe.

**Comment by jadamcrain** [comment]
Hi Felipe,

Which branch are you using? dnp3.github.com and github.com/automatakllc/dnp3 are a commercial forked maintained by Automatak (www.automatak.com).

The link you provided is the original project operated by Green Energy Corp (GEC).

The two project should be wire compatible via the standard, but have somewhat different API's at the this point.

Please post this question to the appropriate list:

http://groups.google.com/group/open-dnp3 (GEC)
http://groups.google.com/group/automatak-opendnp3 (Automatak)

If it get's posted to the Automatak branch, I'll try to answer the question there. After a first read, I'm not sure exactly what you mean.

thanks,
Adam

**Comment by faburaya** [comment]
Hi, Adam. Thanks for your answer. I am using the Automatak branch to implement the master. The slave simulator, however, was written in java and makes use of the original GEC implementation. I am aware of the differences. I am posting it now in the link you have just provided me.

**Comment by jadamcrain** [comment]
Cool. Thanks for the clarification. Just write the question up and send it  here:

http://groups.google.com/group/automatak-opendnp3

This just makes sure questions get addressed in one place and people can search for answers.
