### ISSUE TITLE
event timetag

### ISSUE THREAD

**Issue by oppybob** [dnp3/opendnp3#144]
events generated by the sample application outstation do not contain a valid timetag

**Comment by jadamcrain** [comment]
Agreed that this would make the demos better. Just need to use overloaded constructors for Binary/Analog/Counter/etc that accept a time value.

**Comment by jadamcrain** [comment]
Added this in bd6ada8930cb87a3cfcbdb0ecf8309fd644bd356 for 2.1.0-RC5 tag.
