### ISSUE TITLE
Duplicated notification of events

### ISSUE THREAD

**Issue by mpvillada** [dnp3/opendnp3#153]
A change in an outstation analog\* value causes two notifications of that same value in the master. It happens randomly, so it appears to be some kind of race condition.

*It also happens with the rest of the datatypes: Binaries, DoubleBit... But we are checking just analogs to make it easier to follow the data.

It can be reproduced with this project:
[https://github.com/mpvillada/Dnp3BugTest](https://github.com/mpvillada/Dnp3BugTest)

**_This is the setup:_**
We set up a master and an outstation. The outstation is configured with 256 Analogs.

The master is configured with an AllEventClasses poll every 500ms.

The outstation changes 100 random analogs to random values every 1000ms. Then we proceed to listen to all the data that comes from the DNP3 interface and check it against the data that has been changed in the outstation. Every data change in the outstation must be notified just one time. When running the test, after a while, some data comes replicated in the ISOEHandler.

We can see the data is replicated because we are assigning random values to the analogs, so the values are unlikely to be repeated.

**Comment by jadamcrain** [comment]
I believe that the failures you're seeing are do to some defects in the test itself, namely:

1) Performing an integrity poll on startup and not throwing out static values
2) Randomly setting the event buffer sizes. If these are too small, a lose of synchronization can occur causing an integrity poll, which in turns causes a false event duplication.

I've written an integration test in C++ that attempts to capture the essence of your test, but provides strong guarantees that event production is throttled so as to never overflow the buffers. The startup integrity poll is also explicitly disabled:

https://github.com/automatak/dnp3/blob/2.0.x/cpp/tests/asiodnp3tests/src/TestEventIntegration.cpp#L226

If you can think of any way to modify the test that could should a bug/issue, please let me know.
