### ISSUE TITLE
Cannot perform output commands on IMasterSession

### ISSUE THREAD

**Issue by dwiley007** [dnp3/opendnp3#165]
The issue is in MasterSessionStack::DirectOperate and MasterSessionStack::SelectAndOperate

It gets stuck in an infinite loop as it continually calls itself:

self->DirectOperate

It should be calling DirectOperate on the context:

self->m_context.DirectOperate

Would you like me to fix this on the gprs branch?

**Comment by jadamcrain** [comment]
Yes please, good catch.

**Comment by dwiley007** [comment]
Created https://github.com/automatak/dnp3/pull/166

Same issue for some other scans too.

**Comment by jadamcrain** [comment]
Ok, great.
