### ISSUE TITLE
Improve diagnostics when certificate is rejected

### ISSUE THREAD

**Issue by sidhoda** [dnp3/opendnp3#178]
To improve diagnostics when a certificate is rejected for listener-accepted connection:
1. Log the error code returned from X509_STORE_CTX_get_error
2. Call AcceptConnection passing through preverified as a parameter, the application then has a chance to log the fact and optionally accept anyway

**Comment by sidhoda** [comment]
@jadamcrain would it be best target 2.0.x or development branch for this?

**Comment by jadamcrain** [comment]
development branch.
