### ISSUE TITLE
Channel statistics no longer updated

### ISSUE THREAD

**Issue by sidhoda** [dnp3/opendnp3#182]
Previously various channel stats were updating in PhysicalLayerBase. Looks like this has been lost in the recent refactoring on the development branch

**Comment by jadamcrain** [comment]
Thanks. Will get this fixed up before RC.

**Comment by jadamcrain** [comment]
I've restored the events on LinkChannelStatistics:

https://github.com/automatak/dnp3/commit/fdfb19bc9262566f186b5f659ed54701d81daf6c

Try this out and let me know.

**Comment by sidhoda** [comment]
Works fine with fix applied in #185

**Comment by jadamcrain** [comment]
I've merged the PR. Thanks for testing and fixing.
