### ISSUE TITLE
Example outstation isn't configured correctly

### ISSUE THREAD

**Issue by chk-mk** [dnp3/opendnp3#186]
I noticed the example outstation was not returning floating point values for analog 0 despite apparently being set to group 30 var 5. Looks like 65267ea changed how database configuration is done. The TLS example was updated to configure it before outstation creation but the non-TLS example was not.

Is this now the correct way to set it up?

**Comment by jadamcrain** [comment]
Thanks for letting me know. The TLS example is correct, and the regular example needs to be fixed.

I'll close this once I've had a chance to do this.

**Comment by jadamcrain** [comment]
Fixed in 8e353146b35724680c7797e5adc2d754e1d745dd.

Will be part of next RC
