### ISSUE TITLE
Unnecessary duplicated callbacks inside ICommandHanlder

### ISSUE THREAD

**Issue by mprync** [dnp3/opendnp3#196]
This is a suggestion and not really an issue.

[ICommandHandler.cs](https://github.com/automatak/dnp3/blob/2.0.x/dotnet/bindings/CLRInterface/ICommandHandler.cs#L51)

> CommandStatus Select(ControlRelayOutputBlock command, ushort index);
> CommandStatus Select(AnalogOutputInt32 command, ushort index);
> CommandStatus Select(AnalogOutputInt16 command, ushort index);
> CommandStatus Select(AnalogOutputFloat32 command, ushort index);
> CommandStatus Select(AnalogOutputDouble64 command, ushort index);

These seem irrelevant and short hand versions for "Select & Operate".

Seems odd to have separate ones for this type and not the others. I would suggest removing them since you can handle all operate types within the other (main) methods.

**Comment by jadamcrain** [comment]
@InFaMoUsZero Hi. The select methods are not shorthand for SBO. The outstation application isn't supposed to actually perform the control action when Select(...) is called. You're just telling the master if a subsequent Operate message will succeed for the point in question. Does this make sense?

We should update the method documentation to make this clear. There's some companion documentation that describes this in more detail here:

https://automatak.com/opendnp3/docs/guide/current/api/outstations/#icommandhandler

Operate(..) may be called either when a valid SBO sequence is performed, or when a Direct Operate or DirectorOperateNoAck is sent. You can tell which method was used from the OperateType opType parameter.
