### ISSUE TITLE
DNP3 Decoder example not compiling

### ISSUE THREAD

**Issue by senormeow** [dnp3/opendnp3#205]
I am trying the compile the example decoder. When I enable the DNP_DECODE in the demo  `if(DNP3_DECODE)` line [175 of CMakeLists.txt ](https://github.com/automatak/dnp3/blob/2.0.x/CMakeLists.txt#L175)  to build the decoder demo, I get the following error:
```
/main.cpp:22:37: fatal error: openpal/logging/LogRoot.h: No such file or directory
compilation terminated.
CMakeFiles/decoder.dir/build.make:62: recipe for target 'CMakeFiles/decoder.dir/cpp/examples/decoder/main.cpp.o' failed
make[2]: *** [CMakeFiles/decoder.dir/cpp/examples/decoder/main.cpp.o] Error 1
CMakeFiles/Makefile2:260: recipe for target 'CMakeFiles/decoder.dir/all' failed
make[1]: *** [CMakeFiles/decoder.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jadamcrain** [comment]
There was a typo in CMakeLists.txt that caused the demo for the decoder to not build when passed "DNP3_ALL".  I fixed this and modernized the demo program in 957518e7a182d23cd5da46c4a74a53e3b59e2ac9.

FYI, the decoder library was really just meant to enable this project:

https://github.com/automatak/dnp3cgi

for the homepage CGI decoder.
