### ISSUE TITLE
C sharp outstation time reporting

### ISSUE THREAD

**Issue by dupes** [dnp3/opendnp3#211]
When recording time, the C# outstation isn't converting to UTC: https://github.com/automatak/dnp3/blob/2.0.x/dotnet/bindings/CLRInterface/Conversions.cs#L70.  

The time created in `Conversions.cs` done be done the same as here: https://github.com/automatak/dnp3/blob/2.0.x/dotnet/bindings/CLRInterface/IMasterApplication.cs#L112

**Comment by jadamcrain** [comment]
Resolved in a9a2c0de4abecdb7f068551829ca25090dc19dcb
