### ISSUE TITLE
C# Outstation leaks memory when loading measurement updates

### ISSUE THREAD

**Issue by jadamcrain** [dnp3/opendnp3#213]
https://github.com/automatak/dnp3/blob/2.0.x/dotnet/bindings/CLRAdapter/src/ChangeSetAdapter.h#L23

ChangeSetAdapter has no finalizer that frees native resource

**Comment by jadamcrain** [comment]
Proposed fix in 915cc963efead09c2ae6273645068024474ae412

**Comment by jadamcrain** [comment]
Reopening since there are reports that this still leaks. Need to do profiling to see why finalizer isn't being called.

**Comment by samhightech** [comment]
I have been using opendnp3 using nuget in my C# Windows service, I update 5000 values each 5 seconds, and the ram is getting full in a crazy way, due to the changesets, please I need some guidance to fix this issue asap, the leakage is so obvious.

**Comment by jadamcrain** [comment]
Try the 2.3.0-M1 release:

https://www.nuget.org/packages/opendnp3/2.3.0-M1

**Comment by samhightech** [comment]
Yeah it minimized the memory leak, I have been investigating it for a while, thanks.

Also I want to ask about one off topic issue, regarding GI from my outstation, and time sync when asked by Master, how can I customize it, or is it already implemented?

**Comment by emgre** [comment]
I was not able to find any leaks in the C# bindings in the 2.3.0-M1 release. I did some formating and a small optimisation in PR #276.
