### ISSUE TITLE
Support IEEE 1815-2012 / 2016 standard ? Subset Definitions Level ?

### ISSUE THREAD

**Issue by gadh** [dnp3/opendnp3#220]
does your CPP/C# ports support these new standards ?
and which DNP3 Subset Definitions levels you support in C#/CPP ?

**Comment by jadamcrain** [comment]
https://www.automatak.com/opendnp3/docs/guide/current/features/features/

**Comment by gadh** [comment]
thanks, but this page does not specify the exact standard supported (2010/2012/2016).

**Comment by jadamcrain** [comment]
There's really not much difference in the subset tables for IEEE 2010 vs 2012.  This is based off of 2012. There is no 2016.

**Comment by gadh** [comment]
thanks
should i use the sw stack v 1.1.0 or 2.2.x from your site ? what is the difference ?

**Comment by jadamcrain** [comment]
2.2.x is the only supported branch now. 1.1.x was supported until 2.2.x reached feature parity.
