### ISSUE TITLE
C#: Adjustment for the time zone of the time sync sent by the master

### ISSUE THREAD

**Issue by senyordavid** [dnp3/opendnp3#222]
Hi,

Is there any provision in C# that would allow for the adjustment of the Time zone of the time sent to the outstation during a time sync event? The master always sends UTC time on time sync. I think this would be helpful since not all implementations use UTC for timestamps, e.g. using local time. Thanks.

fsociety-uentity

**Comment by jadamcrain** [comment]
Yes,  when you create the master there's a callback interface called IMasterApplication. There's a method for getting the time since epoch that you can override.
