### ISSUE TITLE
cant compile DNP3CLRAdapter in the .NET binding due to missing osslcrypto.lib file

### ISSUE THREAD

**Issue by gustavowd** [dnp3/opendnp3#223]
This is the error:
Erro	LNK1104	não é possível abrir o arquivo 'C:\Users\gusta\Documents\git\dnp3\Debug\lib\osslcrypto.lib'	DNP3CLRAdapter	C:\Users\gusta\Documents\git\dnp3\dotnet\bindings\CLRAdapter\LINK	1	

I´m using x64 with TLS enabled.

**Comment by jadamcrain** [comment]
Please take this question to the mailing list:

http://groups.google.com/group/automatak-dnp3
