### ISSUE TITLE
dotnet: Writing Time and Date using Master.PerformFunction() does not write MillsSinceEpoch to Outstation

### ISSUE THREAD

**Issue by senyordavid** [dnp3/opendnp3#224]
Code:

master.PerformFunction("time_sync", FunctionCode.WRITE, new Header[] { Header.Count8(50, 1, 1) }, TaskConfig.Default);

It only writes the Header but does not write the time itself to the outstation.

**Comment by jadamcrain** [comment]
Correct. PerformFunction can only be used with the 0x06 (all objects) qualifier. 

The master currently doesn't support writing the time through through the external API. It only does so in response to the outstation requesting it w/ the NEED_TIME IIN bit.
