### ISSUE TITLE
How can I use this library to deserialize DNP3 responses to DNP3 Objects? 

### ISSUE THREAD

**Issue by cdbierl** [dnp3/opendnp3#226]
Greetings,

I have created a DNP3 protocol gateway program that intercepts DNP3 IP packets and transforms them for use over a serial interface to communicate with a serial-based RTU. So the code is fairly basic and knows very little, if anything, about the DNP3 protocol. I am looking for a library that can deserialize the responses of the RTU into programmer friendly objects for inspection and manipulation. So basically a library that can take a DNP3 response byte buffer and give me back some mutable objects. My particular use case requires me to inject "Time & Date" objects into the RTU response payload, or simply override existing time/date response object values with that of my DNP3 protocal gateway server.

If I am at the right place, can you provide a small snippet that could point me in the right direction? I saw the decoder example, but that did not appear to provide mutable objects for a programmer to work with.

Thanks.

**Comment by jadamcrain** [comment]
Hi,

We usually try to get these kinds of question onto the mailing list.

https://groups.google.com/forum/#!forum/automatak-dnp3

Join and post the question there and I'll get you an answer!

Thanks,
Adam
