### ISSUE TITLE
JNI master crash when calling Channel.Shutdown() when re-establishing a connection

### ISSUE THREAD

**Issue by jadamcrain** [dnp3/opendnp3#228]
https://groups.google.com/forum/#!topic/automatak-dnp3/CdQ64ZahAvc

**Comment by jadamcrain** [comment]
A user reported a similar issue in the C++ under the right conditions, which I have been able to resolve in this branch:

https://github.com/automatak/dnp3/tree/bug/deadlock_and_lifetimes

There was a race condition in the TCPClientIOHandler which caused an empty shared_ptr to be deferenced.

I believe this is the same issue that caused the segfault in the Java bindings.

**Comment by emgre** [comment]
Fixed in #265.
