### ISSUE TITLE
Outstation not respecting default analog event variations

### ISSUE THREAD

**Issue by ncasaleiro** [dnp3/opendnp3#236]
config.analog[0].svariation = StaticAnalogVariation::Group30Var5;
	config.analog[0].evariation = EventAnalogVariation::Group32Var7;

With Group32Var7   doesn't send timestamp. But with Group32Var5 sends timestamp. I think It is a bug. 
But I don't have much experience under DNP3.

**Comment by ncasaleiro** [comment]
when occurring at an event. By polling sends timestamp.

**Comment by jadamcrain** [comment]
The issue is that the correct way to assign the default variation is:

```
db.analogs[0].config.evariation = EventAnalogVariation::Group32Var5;
```

or

```
db.analogs[0].config.evariation = EventAnalogVariation::Group32Var7;
```

Not

```
db.analogs[0].event.evariation = EventAnalogVariation::Group32Var5;
```

This is very confusing and we plan to improve the API in the next major release.
