### ISSUE TITLE
TaskConfig::With taking a reference with an undetermined lifetime

### ISSUE THREAD

**Issue by emgre** [dnp3/opendnp3#238]
[This](https://github.com/automatak/dnp3/blob/e00ff31b837821064e5208c15866a9d46f8777b1/cpp/libs/include/opendnp3/master/TaskConfig.h#L51-L54) member function is taking a reference to a `ITaskCallback` and only stores a pointer of it. However, this callback must live for the whole request/response lifetime.

A primitive:
```
{
     FooTaskCallback cb{} // inherits from ITaskCallback
     master->ScanRange(opendnp3::GroupVariationID(30, range.variation), 0, 10, opendnp3::TaskConfig::With(cb));
}
```
will segfault due to the callback going out of scope.

The `ITaskCallback` should be taken by `shared_ptr` in order to correct the issue.

**Comment by emgre** [comment]
It would also be nice to have a wrapper that executes a lambda on the `OnComplete`. I have implemented my own like that:

```
#include "opendnp3/master/ITaskCallback.h"

class LambdaTaskCallback : public opendnp3::ITaskCallback
{
public:
    LambdaTaskCallback(std::function<void(opendnp3::TaskCompletion)> cb)
        : m_callback{cb}
    {}

    void OnStart() override {}
    void OnDestroyed() override {}

    void OnComplete(opendnp3::TaskCompletion result) override
    {
        m_callback(result);
    }

private:
    std::function<void(opendnp3::TaskCompletion)> m_callback;
};
```

This is useful for one-time requests and provides similar usage as `ICommandProcessor` where we pass a simple `std::function<void(const ICommandTaskResult&)>`.

**Comment by jadamcrain** [comment]
We'll take  a comprehensive look at the way all of the master API methods make use of callbacks in 3.0.0.

**Comment by emgre** [comment]
The callback handler is taken by `shared_ptr` now.
