### ISSUE TITLE
Unable to access the timestamp for an event

### ISSUE THREAD

**Issue by henkbredell** [dnp3/opendnp3#241]
how do I get the timestamp for the event data obtained from the SOE Handler?
The following log is received on an analog event. 

ms(1530882872361) --AL->  TCV300002 - D1 00 
ms(1530882872361) --AL->  TCV300002 - FIR: 1 FIN: 1 CON: 0 UNS: 1 SEQ: 1 FUNC: CONFIRM
ms(1530882872929) <-AL--  TCV300002 - FIR: 1 FIN: 1 CON: 0 UNS: 0 SEQ: 0 FUNC: RESPONSE IIN: [0x08, 0x00]
ms(1530882872929) INFO    TCV300002 - Begining task: Startup Integrity Poll
ms(1530882872929) --AL->  TCV300002 - C1 01 3C 02 06 3C 03 06 3C 04 06 3C 01 06 
ms(1530882872929) --AL->  TCV300002 - FIR: 1 FIN: 1 CON: 0 UNS: 0 SEQ: 1 FUNC: READ
ms(1530882872929) --AL->  TCV300002 - 060,002 - Class Data - Class 1 - all objects
ms(1530882872929) --AL->  TCV300002 - 060,003 - Class Data - Class 2 - all objects
ms(1530882872929) --AL->  TCV300002 - 060,004 - Class Data - Class 3 - all objects
ms(1530882872929) --AL->  TCV300002 - 060,001 - Class Data - Class 0 - all objects
ms(1530882873729) <-AL--  TCV300002 - FIR: 1 FIN: 1 CON: 1 UNS: 1 SEQ: 2 FUNC: UNSOLICITED_RESPONSE IIN: [0x00, 0x00]
ms(1530882873729) <-AL--  TCV300002 - 032,004 Analog Input Event - 16-bit With Flag and Time, 8-bit count and prefix [1]
ms(1530882873729) <-AL--  TCV300002 - 032,004 Analog Input Event - 16-bit With Flag and Time, 8-bit count and prefix [1]
ms(1530882873729) <-AL--  TCV300002 - 032,004 Analog Input Event - 16-bit With Flag and Time, 8-bit count and prefix [1]

The following data is extracted from the event, except the timestamp.  The one shown below is when I receive the data and not when the event is logged in the slave.

{"device":"TCV300002", "qualif":"0_23", "tsmode":"1", "stat":"0", "ts":1530882873000, "values":{"32_4_14":22,"flagsValid":"1"}}

I do not know which classes::members to use from the library to access timestamps for each received event, when the ts_mode is 1.

Thanks in advance
Henk

**Comment by jadamcrain** [comment]
Please move this discussion to the mailing list:

http://groups.google.com/group/automatak-dnp3
