### ISSUE TITLE
Outstation accepts bad database configuration in discontiguous index mode.

### ISSUE THREAD

**Issue by emgre** [dnp3/opendnp3#244]
When an outstation is created with `IndexMode::Discontiguous`, it expects that the points are sorted by index value. However, if the user does not order the points, the library does not advertise the misconfiguration and updates may fail later on (because of the binary search expecting the points to be ordered).

- The library should advertise in case of misconfiguration of the database or sort the points by itself.
- The documentation should be updated to emphasize the fact that it expects the points to be ordered (if it's not already the case, but I couldn't find where it said so)

**Comment by jadamcrain** [comment]
Resolved in [PR 296](https://github.com/dnp3/opendnp3/pull/296)
