### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by SaeedMoradpour** [dnp3/opendnp3#250]
Hi!
I have been successful cross compiling outstation-demo using openGDB for armbian(orangePI r1). I have a problem which I do not know how to handle it. How can I add mysql to this project? If I should change the makefile, how?
 Thanks!

**Comment by jadamcrain** [comment]
Install opendnp3 as a library:

> sudo make install

The default location will be /usr/local/lib and /usr/local/include

You can then use opendnp3 like any other library in your project that integrates it w/ mysql.
