### ISSUE TITLE
Reimplement discontiguous index mode

### ISSUE THREAD

**Issue by jadamcrain** [dnp3/opendnp3#261]
The API allows for non-valid configurations. It would be way better to pass in a set of maps  (i.e. map<index, point-info>). We can then provide optimized back-end implementations based on:

1) Arrays for continuous indices
2) std::map for discontinuous mode

There are enough issues with the way this feature is currently implemented to warrant a complete re-work of the feature using a saner approach.

**Comment by emgre** [comment]
See also #244.

**Comment by jadamcrain** [comment]
If this is backed by std::map, you can use [lower_bound](https://en.cppreference.com/w/cpp/container/map/lower_bound) when searching the map using range.

Say a master asks for points 4 - 7 but only 5 - 8 are defined.  `lower_bound(4)` will return an iterator pointing to 5.

**Comment by jadamcrain** [comment]
Resolved in [PR 296](https://github.com/dnp3/opendnp3/pull/296)
