### ISSUE TITLE
Java API - ListenableFuture with get(timeout) mechanism

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#28]

**Comment by jadamcrain** [comment]
Note:

Timeout is currently controlled implicitly via application layer response timeouts.

**Comment by cverges** [comment]
I think that the mechanism you described relies on the DNP3 stack to properly trigger the timeout.  What if the stack gets hosed up?  The caller should have a way of specifying some "maximum wait time" such that a Java TimeoutException is thrown rather than returning a CS_TIMEOUT.

**Comment by jadamcrain** [comment]
Yeah, agreed. I don't see how it can hurt to add this overload. The two competing timeouts will just need to be documented well.

Stack makes the guarantee to set the value, but deadlock could occur if stack gets boned.

**Comment by jadamcrain** [comment]
Done on 2.0.x.

void get(long timeoutMs) throws TimeoutException
