### ISSUE TITLE
Add support for on-demand polling by a Master

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#29]
Certain kinds of physical layers (such as cellular) incur cost per byte transferred.  For these units, we want the integrity polling interval to be very large by default.  Exception scans are used to fill in the gaps.

However, when we issue a output write (such as an analog output or binary output), we want to temporarily increase our polling frequency so that we can positively detect the "set" operation via a change in the corresponding output status points.  As the output status points are not sent during a standard exception scan, what is needed is a way to either adjust the integrity poll period on the fly or enable an external agent to instruct the Master to perform an integrity poll on-demand.  (The scheduling can be then handled by the external agent.)

**Comment by jadamcrain** [comment]
Yeah. I think this is a good one. I want the API to be extended to add "Scans" to the master interface. These scans could then be disabled, triggered on demand, or have their period altered.

**Comment by jadamcrain** [comment]
Added to 2.0.x
