### ISSUE TITLE
migrate library to use header-only Automatak libs

### ISSUE THREAD

**Issue by jadamcrain** [dnp3/opendnp3#290]
https://github.com/automatak/ser4cpp
(similar functionality now in openpal)

https://github.com/automatak/exe4cpp
(similar functionality now in openpal/asiopal)

https://github.com/automatak/log4cpp
(similar functionality now in openpal)

Additionally, regarding the public API:

* ser4cpp should be completely private (eventually). The octet strings currently use RSlice but we can make this a dirt simple buffer class `struct { pointer, length }` for the public API. The layer interfaces use this as well, but they'll be private once we smash the 4 separate libs down to a single library/namespace.

* exe4cpp should be completely private. DNP3Manager allocates the StrandExecutor internally.

* log4cpp could be private if we want to provide our own shim ILogHander/LogEntry? It might be worth it so that the public API can be completely free of log4cpp types.

**Comment by emgre** [comment]
This is done in the develop branch.
- The library is now a single target called `opendnp3`.
- `openpal` doesn't exist anymore.
- `ser4cpp`, `exe4cpp` and `log4cpp` are now used.
- `ser4cpp` and `exe4cpp` are completely private, so the user doesn't need them to build something.
- Hiding `log4cpp` from the public interface needs some more reflexion.

**Comment by jadamcrain** [comment]
What do we lose by not hiding log4cpp::ILogHandler/etc? We can install it like any other header, but usually libraries like to install themselves.

**Comment by emgre** [comment]
`log4cpp` was completely copied into opendnp3, so that we have no public dependencies.
