### ISSUE TITLE
Use exceptions instead of error_code

### ISSUE THREAD

**Issue by jadamcrain** [dnp3/opendnp3#293]
Opendnp3 **never** uses exceptions internally, but they make a lot of sense for parts of the public API, e.g. when you add a channel to the DNP3Manager with bad configuration.

**Comment by blytkerchan** [comment]
FWIW The way I usually address this in public-facing APIs is by having everything internally not use exceptions, and defining the outer APIs as non-throwing with an  `std::nothrow_t const&` parameter and an overload without that parameter that does throw.

Example from RTIMDB:
```
#ifdef RTIMDB_ALLOW_EXCEPTIONS
	void sendCommand(unsigned int point_id, Details::CROB const &crob);
#endif
	Errors sendCommand(unsigned int point_id, Details::CROB const &crob RTIMDB_NOTHROW_PARAM);

```
In this case, when `RTIMDB_ALLOW_EXCEPTIONS` is defined, `RTIMDB_NOTHROW_PARAM` expands to `std::nothrow_t const& whereas if it's not defined, it expands to an empty string. This allows applications that don't use exceptions not to bother with putting std::nothrow in all their calls, and applications that do use exceptions keep the choice.

HTH

**Comment by emgre** [comment]
Exceptions are now thrown only in `DNP3Manager` (so at startup). Also, we validate that we can bind to the port at creation of a channel and throw if we cannot (because it represents a misconfiguration).
