### ISSUE TITLE
does not have binary files after build

### ISSUE THREAD

**Issue by wyc8** [dnp3/opendnp3#295]
I am using v3.0.0. I used below commands to build: 
_cmake ../dnp3 -DDNP3_DEMO=ON -DDNP3_TLS=ON_
There is an error "-- clang-format not found", and "--clang-tidy not found". 
_make -j_
It builds to .o file: building CXX object cpp/lib/CMakeFiles/opendnp3.dir/src/.... .o
100% Linking CXX static library libopendnp3.a
100% Built target opendnp3
But I do not find master-demo and outstation-demo files.

**Comment by emgre** [comment]
The 3.0.0 branch is not stable at all and is currently in development, you should not be using it. Please prefer the latest release in the `master` branch.

For your curiosity, `DNP3_DEMO` was renamed `DNP3_EXAMPLES` as you can see [here](https://github.com/dnp3/opendnp3/blob/3.0.0/CMakeLists.txt#L22).
