### ISSUE TITLE
Application control of NEED_TIME IIN bit

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#30]
For some systems, allowing the DNP stack to control the IIN NEED_TIME bit is sufficient.  For others with dedicated time-keeping devices (such as GPS time sync or cellular radios), a more precise time can be determined from these external sources.  It would be beneficial if the application layer could control the stack's automatic use of the IIN NEED_TIME bit in such circumstances.  (Like a "disable / enable" flag that operates at runtime.)

**Comment by jadamcrain** [comment]
Agreed.  I'll add SetNeedTimeIIN() to the Outstation interface in 1.2.x series.

**Comment by cverges** [comment]
Will this new API replace the existing timer loop?  That is, are you planning to completely offload the time management to the application layer?  (+1 if so!  I think it's the proper abstraction, though providing a "simple" timer as a courtesy for those who don't want to deal with it on their own is also nice.)

**Comment by jadamcrain** [comment]
I would probably leave the existing timer option in place, at least for 1.2.x.  User's wanting manual control will simply disable it in configuration (or not enable it since disabled is the default) and then set the bit using the API method on demand.

**Comment by cverges** [comment]
That sounds like a great method.  Thanks for the extra details!

**Comment by jadamcrain** [comment]
Done. Very simply addition to 2.0.x.

You can now set the bit regardless of whether the timer is enabled or not.
