### ISSUE TITLE
Flow control not set on ASIO serial port

### ISSUE THREAD

**Issue by JacquelineArt** [dnp3/opendnp3#305]
In https://github.com/dnp3/opendnp3/blob/master/cpp/libs/src/asiopal/ASIOSerialHelpers.cpp
Adding just these two lines of code to function Configure() solves the problem.

	port.set_option(ConvertFlow(settings.flowType), ec);
	if (ec) return false;

**Comment by jadamcrain** [comment]
thank you. Will get this into a bug release.

**Comment by jadamcrain** [comment]
Applied in a0512ac4fcdc892a70ed2c128110985d7e290d12

Will be part of upcoming 3.0.0
