### ISSUE TITLE
expose option to disable CRC checking when fuzzing

### ISSUE THREAD

**Issue by jadamcrain** [dnp3/opendnp3#306]
https://github.com/dnp3/opendnp3/blob/develop/cpp/lib/src/link/CRC.cpp

We need this preprocessor directive set when building in OSS Fuzz so that most things get past the link layer.

**Comment by emgre** [comment]
The flag gets set automatically by libfuzzer when we build it for OSS-Fuzz. See https://llvm.org/docs/LibFuzzer.html#fuzzer-friendly-build-mode

**Comment by jadamcrain** [comment]
Oh, interesting. I didn't realize that. Let's re-purpose this ticket then to add a comment to that line to explain how the directive gets set.

**Comment by emgre** [comment]
Comment added in https://github.com/dnp3/opendnp3/commit/9335ce5212de65f454ca451acd9e546f3716f730.
