### ISSUE TITLE
run circle CI builds w/ additional CXX flags

### ISSUE THREAD

**Issue by jadamcrain** [dnp3/opendnp3#307]
To avoid warnings from piling up during development, let's get our CI builds using these options:

```
-DCMAKE_CXX_FLAGS="-Wall -Werror"
```

**Comment by emgre** [comment]
It's done, but we exclude `-Wformat-truncation`, because the warnings are not important.

Do we want to add `-Wextra` ?

**Comment by jadamcrain** [comment]
It depends if there are warnings that are actually useful

**Comment by emgre** [comment]
`-Wextra` adds a couple of interesting warnings, most notably `sign-compare` and `type-limits`. But it also adds the very noisy and irrelevant `unused-parameter` that I manually disabled.

Added in https://github.com/dnp3/opendnp3/commit/d52c9103507fb93a270884309cc005b2cb25ddaa and https://github.com/dnp3/opendnp3/commit/908fcf060f1a806da2be0023c5cf9e2c6472ab4a.
