### ISSUE TITLE
Empty DataObserver transactions being reported to the application

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#32]
The DataObserver start() / end() methods are being called without any calls to update() in between.  This "null" behavior isn't bad, just annoying and not useful.

**Comment by jadamcrain** [comment]
This is fixed in 2.0.x now with new API design.  Not sure if it's worth trying to backport to 1.1.x.

**Comment by jadamcrain** [comment]
Fixed on 2.0.x, wontfix for 1.0.x
