### ISSUE TITLE
Install not created

### ISSUE THREAD

**Issue by JakeGridEdge** [dnp3/opendnp3#326]
When following the build process on GitHub, following a make -j there is supposed to be a make install call. After using cmake and make, no install file was ever created in my library. Is there no install file anymore or is it somewhere other than the made dnp3 directory?

**Comment by jadamcrain** [comment]
Version of opendnp3 and Linux platform? We'll give it a try.

**Comment by xaoxtheory** [comment]
Ran into the same problem on Ubuntu 19.04 using the default branch (which is develop at the moment). Got everything working by checking out the release-2.x branch.

**Comment by jadamcrain** [comment]
Yes, stick to a tagged release. Massive refactoring and changes taking place on develop, including to the CMake configuration.
