### ISSUE TITLE
opendnp3/app/Flags.h file lack overloads for DoubleBitBinaryQuality enum class

### ISSUE THREAD

**Issue by arturioxas** [dnp3/opendnp3#327]
While porting the library I ran into a problem where I could not access DoubleBitBinaryQuality. Short research showed that while proper enum class is there, no overloads are written to access it. I would very much like to know if that was a conscious decision, and if not, I would later propose a pull request.

**Comment by jadamcrain** [comment]
Probably an oversight. We will investigate before next release.

**Comment by emgre** [comment]
The missing overloads and unit tests were added in the develop branch in commit c1e43b9b38094f222af04cba31dcffb9bdb95bf9.
