### ISSUE TITLE
Is there a compilable version with Octets?

### ISSUE THREAD

**Issue by JakeGridEdge** [dnp3/opendnp3#331]
On the google docs page, https://dnp3.github.io/docs/guide/current/features/features/, it says that there is Octet support with DNP3. Is there a branch or version with the compilable demos and octet support?

**Comment by emgre** [comment]
Yes, the 2.x version supports Octet String (group 110/111).

For an outstation example, look [here](https://github.com/dnp3/opendnp3/blob/release-2.x/cpp/examples/outstation/main.cpp#L163-L169). It updates an Octet String.

On the master side, you will receive updates through the `ISOEHandler` [here](https://github.com/dnp3/opendnp3/blob/release-2.x/cpp/libs/include/opendnp3/master/ISOEHandler.h#L56)
