### ISSUE TITLE
Combining Data Types

### ISSUE THREAD

**Issue by JakeGridEdge** [dnp3/opendnp3#332]
If I wanted to define my outstation with 3 datatypes (10 Analog In, 10 Analog Out, and 50 Octets), how would I combine them before placing them in "OutstationStackConfig config(DatabaseSizes::________);"?

**Comment by jadamcrain** [comment]
HI @JakeGridEdge. Are you a member of the mailing list? I'd prefer if we kept these kind of discussions there:

https://groups.google.com/forum/#!forum/automatak-dnp3

**Comment by JakeGridEdge** [comment]
Yes! I'll go post it there now. Thank you
