### ISSUE TITLE
How to use outstation-demo ?

### ISSUE THREAD

**Issue by allenyummy** [dnp3/opendnp3#333]
I have been compiled successfully by using the command 
`cmake ../dnp3 -DDNP3_DEMO=ON -DDNP3_TLS=ON` 
And then I run the "./outstation-demo" and got this:
![image](https://user-images.githubusercontent.com/36063123/62832786-b6bc7180-bc66-11e9-92ea-d58581eebbf9.png)

My question is how to build the master and outstation. 
Thanks for replies.

**Comment by JakeGridEdge** [comment]
You need to set the TCP server address on the device running the Outstation code. Go to /opendnp3/cpp/outstation/main.cpp and edit the ip on the line "auto channel = manager.AddTCPServer()" to the server address.

**Comment by allenyummy** [comment]
Thanks, I got it!
