### ISSUE TITLE
Event stack never emptied when events are read

### ISSUE THREAD

**Issue by adou07** [dnp3/opendnp3#336]
The events are not removed from event stack after they are read by master with an application scan.
I think that "EventStorage::ClearWritten()" is never reached.

I use 2.3.0 version

Master configuration:
master application instance: siodnp3::DefaultMasterApplication::Create()
(asiodnp3::MasterStackConfig *)->link.UseConfirms = true;
(asiodnp3::MasterStackConfig *)->master.disableUnsolOnStartup = true;

Outstation configuration:
outstation application instance: DefaultOutstationApplication::Create()
(asiodnp3::OutstationStackConfig *)->link.UseConfirms = true
(asiodnp3::OutstationStackConfig *)->outstation.params.allowUnsolicited = false

**Comment by jadamcrain** [comment]
HI @adou07. Can you provide any pcaps showing this behavior?
