### ISSUE TITLE
DNP3 class data base configuration behaviour

### ISSUE THREAD

**Issue by adou07** [dnp3/opendnp3#337]
Using opendnp3 library, i configure in the outstation some data to be in class 0 and the others in class 1. 
(asiodnp3::OutstationStackConfig *)->dbConfig.analog[index0].clazz = opendnp3::PointClass::Class0; (asiodnp3::OutstationStackConfig *)->dbConfig.analog[index1].clazz = opendnp3::PointClass::Class0; (asiodnp3::OutstationStackConfig *)->dbConfig.analog[index2].clazz = opendnp3::PointClass::Class1; (asiodnp3::OutstationStackConfig *)->dbConfig.analog[index3].clazz = opendnp3::PointClass::Class1;
 When Master requests a scan for class 1 only index2 et index3 are read, however when requests for static scan (class 0) all data are read (index0 index1 index2 index3)! is this a normal behaviour?

**Comment by emgre** [comment]
Yes, it is the normal behaviour. Please refer to IEEE 1815-2012 Section 4.1.5.3.

> If a point is assigned to one of the event classes (Class 1, 2, or 3), the outstation shall store and report events for that point, and the point's present value shall also be reported by the outstation in its response to a Class 0 poll.
