### ISSUE TITLE
Time Synchronization Command

### ISSUE THREAD

**Issue by Yesid8** [dnp3/opendnp3#340]
Time synchronization only works as a server request, in some cases it is necessary to send as a command

**Comment by Yesid8** [comment]
Hi Adam, this item,  do you plan to make a next version?

**Comment by jadamcrain** [comment]
This item will not be in 3.0

**Comment by jadamcrain** [comment]
Opendnp3 is frozen to new features:

https://stepfunc.io/blog/opendnp3-retrospective/
