### ISSUE TITLE
How do I get all the data transferred over tcp socket?

### ISSUE THREAD

**Issue by MortalAndTry** [dnp3/opendnp3#361]
Through DNP3Manager's log interface, I can only get data from the application layer. What should I do if I want to get data from the data link and transport layers?

**Comment by jadamcrain** [comment]
I misread this on the first pass. The log levels define how to get protocol decoding for the link and app layers, for instance:

https://github.com/dnp3/opendnp3/blob/release-2.x/cpp/libs/include/opendnp3/LogLevels.h#L71
