### ISSUE TITLE
Does not build with Asio 1.13.0 and newer

### ISSUE THREAD

**Issue by podsvirov** [dnp3/opendnp3#373]
One of ressones is removing of methods like `get_io_service()`. For more info see [revision history](https://think-async.com/Asio/asio-1.16.1/doc/asio/history.html#asio.history.asio_1_13_0).

**Comment by jadamcrain** [comment]
Known issue, fixed on `develop` branch.

**Comment by podsvirov** [comment]
Good news.  We are waiting for a new release.  Thanks!

**Comment by jadamcrain** [comment]
@podsvirov We have a 3.0 being released soon which migrates to the latest ASIO. Have a look at the new cmake structure on `develop` as it will require changes on on the `vcpkg` end of things.
