### ISSUE TITLE
DNPTime.quality always INVALID for g2v2 event

### ISSUE THREAD

**Issue by sidhoda** [dnp3/opendnp3#377]
When sending a g2v2 unsolicited event to a opendnp3 master (v3.0.1), TypedMeasurement<bool>.time.quality is always INVALID whereas info.tsquality is SYNCHRONIZED. The expected behaviour is that DNPTime.quality and HeaderInfo.tsquality are always in sync.

**Comment by jadamcrain** [comment]
After spirited debate, we've decided how to resolve this discrepancy. This will result in 3.0.2 being released this week.

**Comment by jadamcrain** [comment]
Have a look at this PR @sidhoda:

https://github.com/dnp3/opendnp3/pull/379

**Comment by jadamcrain** [comment]
Resolved in #379
