### ISSUE TITLE
Java: Assertion leClz != __null failure in LogSubscriberAdapter::Log(const LogEntry&)

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#39]
java: java/cpp/LogSubscriberAdapter.cpp:40: virtual void LogSubscriberAdapter::Log(const opendnp3::LogEntry&): Assertion `leClz != __null' failed.

**Comment by jadamcrain** [comment]
Do you have a Java test case that will reproduce?

There is a JUnit based test suite for the adapter if you have time to try and write something to shake this issue out.

**Comment by cverges** [comment]
Not a JUnit test, but it does seem to occur in our main Java application quite frequently.

**Comment by jadamcrain** [comment]
Does it only happen during Startup/Shutdown or have you seen it during steady-state? I assume this would be a lot higher priority of it was during steady state application.

My current working theory is that a log call is happening in the manager on the main thread somewhere, not the thread pool.

**Comment by cverges** [comment]
It occurs within the first few seconds of system startup, but some log messages are relayed, then the null pops up.  Other times, the null happens nearly first.

**Comment by jadamcrain** [comment]
A BIG clue would be finding out what log message is killing it.
i.e., try adding a print statement for the message
that way we can see at what point this is happening.
i.e. if leClz == NULL { print(message); }

**Comment by cverges** [comment]
The log message where it is dying is 4 into the whole process.  It's a Connection Refused message from the master.  So it's working for 3 prior messages, then saying, "I can't find the class!"  WTF?

The context is that this is running inside a Tomcat container.  This same code executes perfectly when running under JUnit.  Definitely some container interaction here.

Thinking maybe related to this: http://stackoverflow.com/questions/13263340/findclass-from-any-thread-in-android-jni

**Comment by cverges** [comment]
Fixed in latest 1.1.x.
