### ISSUE TITLE
Is it possible to do single channel single master with multiple outstations

### ISSUE THREAD

**Issue by mzy2240** [dnp3/opendnp3#391]
I tried to run the master as the TCP server and then connect multiple outstations to it, and it can only get the data from that single outstation with the specified remote address. If I want to have only one master, how should it be able to connect to multiple outstations? Thank you in advance!

**Comment by jadamcrain** [comment]
TCPServer channels only support a single outstation.

Have a look at the master "gprs" example:

https://github.com/dnp3/opendnp3/tree/release/cpp/examples/master-gprs

It allows you to accept multiple connections as a master and handle them based on their link-layer address.
