### ISSUE TITLE
No Time synchronisation, when master is not synchronized.

### ISSUE THREAD

**Issue by jodore** [dnp3/opendnp3#397]
When the outstation needs the time, the library asks the application for the time.
What if the master can´t provide a valid time? (e.g. is not synchronized itself)

Could it be possible to add a parameter to the function "opendnp3::UTCTimestamp Now()" to get information about the validity of the timestamp?

Thanks in advance.

**Comment by jadamcrain** [comment]
That's an interesting wrinkle that the current API just doesn't support.

That said, opendnp3 is on a feature freeze. The current maintainers are only doing bug fixes, not feature additions.

We'd consider merging it if there were a clean PR done, with unit tests, and pushed through the Java/C# bindings.

All of our effort is going into Rust implementations going forward:

https://stepfunc.io/blog/bindings/
