### ISSUE TITLE
Question: Thread safety and usage in a web application

### ISSUE THREAD

**Issue by OOPMan** [dnp3/opendnp3#406]
Hi, I was just wondering what the status is of OpenDNP3 with regards to thread safety and the degree to which it is safe to use it within the context of a web application.

To be more specific, I'm considering both classical synchronous web applications and also asynchronous I/O ones. Is one safer than the other? I know the documentation notes that one should avoid blocking in callbacks to user code, does this imply that an async I/O style web application would be a better fit for OpenDNP3?

Is it safe to create a Managers/Channel/Master/Outstation at the global level and make use of it across different threads handling requests within a web application?

I did some experimental work using OpenDNP3 in the context of a web application but did not get to the point where I was testing this side of things and thus I figured I would ask before proceeding down a bad avenue of development...

On a related note, how safe is it to use multiple DNP3 Managers in the same application?

**Comment by jadamcrain** [comment]
Channel, Master and Outstation interfaces are thread safe, and may be called concurrently from multiple threads. Internally they use message passing to send operations to the DNP3 thread pool.

If scalability is a goal (e.g. many concurrent master connections to outstations) you will want to take care not to block callbacks as they originate from a limited (configurable) number of thread pools threads.

How hard or easy it is to integrate with (a)synchronous web frameworks probably depends a lot on what language you're using. The Java and C# bindings provide great support for Futures upon which you can block or asynchronously chain. The C++ API only provides callbacks so integrated in a synchronous web framework will require some additional work.

If you have further questions, please post to the mailing list:

https://groups.google.com/g/automatak-dnp3
