### ISSUE TITLE
Invalid Time

### ISSUE THREAD

**Issue by steelsurfer** [dnp3/opendnp3#408]
How classy would opendnp3 be (in terms of effort to change) if there were two types of DNP3TIME:-
DNP3TIME(Legacy) and DNP3TIME(Olympic) per attached where:-
DNP3TIME(Olympic) = DNP3TIME(Legacy) x 64   OR   (Ox3F AND Flag Octet)

Thus, DNP3TIME(Olympic) being how to “represent the different states of time” or in effect, a “time quality”?

Reference email: 21 December 2020 3:15AM UTC
Subject: RE: [dnpTC] Invalid time

**Comment by jadamcrain** [comment]
The ship sailed long ago on DNP3 being able to encode time quality, and we are not interested in pursuing non-standard time encodings here.
