### ISSUE TITLE
How to install dotnet library

### ISSUE THREAD

**Issue by Saleem344** [dnp3/opendnp3#409]
Can any one how to install dotnet library?

Thanks for the help.

**Comment by jadamcrain** [comment]
https://dnp3.github.io/docs/guide/3.0.0/build/windows/#net-bindings

https://www.nuget.org/packages/opendnp3/

**Comment by Saleem344** [comment]
Hi,
I want to use this binding in ubuntu, I have used CLI from this link
https://www.nuget.org/packages/opendnp3/
I'm getting error like
1.The type or namespace name 'Adapter' does not exist in the namespace
'Automatak.DNP3.
2. The type or namespace name 'Interface' does not exist in the namespace
'Automatak.DNP3.


Regards,
Saleem.

**Comment by jadamcrain** [comment]
The .net bindings will only work on Windows.

**Comment by Saleem344** [comment]
Hi,
I want to use DNP3 in the Linux platform using *.Net Core*, Can you suggest
something to make it work?
Thank you for your help.
Regards,
Saleem.

**Comment by jadamcrain** [comment]
There is no way to make this library work on .NET Core for Linux. The bindings use C++/CLI to achieve interop with .NET/C++, and can only be built to target windows.

**Comment by Saleem344** [comment]
Ok, thanks.
