### ISSUE TITLE
How can I use this library in Linux?

### ISSUE THREAD

**Issue by Saleem344** [dnp3/opendnp3#413]
Hi,
I want to use  dnp3 in Linux can anyone suggest the installation process?

Thanks for your help.

**Comment by jadamcrain** [comment]
https://dnp3.github.io/docs/guide/3.0.0/build/linux/

**Comment by Saleem344** [comment]
I have already  used this but which programming language should  I use in
Linux ???

**Comment by jadamcrain** [comment]
C++ or Java may be used on Linux. .NET is only possible on Windows.
