### ISSUE TITLE
'DNP3CLRAdapter.dll'

### ISSUE THREAD

**Issue by tran0949** [dnp3/opendnp3#416]
Hi guys, I have a problem with 'DNP3CLRAdapter.dll'. I use opendnp3.2.2.0 (NUGGET) to build my project, but when I built my solution in Visual Studio 2017 It displayed "Could not load file or assembly 'DNP3CLRAdapter.dll' or one of its dependencies. The specified module could not be found". I have installed OpenSSL but it still has the error. I hope everyone can guide me in handling this problem. Sincerely thanks.
![Error](https://user-images.githubusercontent.com/77491412/104725512-c77aec00-5764-11eb-9b3b-517b4b156e3c.png)

**Comment by jadamcrain** [comment]
Use dependency walker on the .dll.  This is caused by either 1) missing C++ runtime or 2) missing openssl:

https://dnp3.github.io/docs/guide/3.0.0/build/windows/#tls-support
