### ISSUE TITLE
Inconsistent return-types in CommandHeader.java

### ISSUE THREAD

**Issue by OOPMan** [dnp3/opendnp3#417]
Hi, the return-types in `java/bindings/src/main/java/com/automatak/dnp3/CommandHeader.java` seem a bit inconsistent.

The following return class `CommandHeader`:
* `fromSingleCROB`
* `fromSingleAO16`
* `fromCROB`
* `fromAO16`

The following return interface `CommandHeaders`:
* `fromSingleAO32`
* `fromSingleAOFloat32`
* `fromSingleAODouble64`
* `fromAO32`
* `fromAOFloat32`
* `fromAODouble64`

This issue also applies to the

**Comment by jadamcrain** [comment]
It should just return the interface type `CommandHeaders`, not the impl type `CommandHeader`.

I think we can safely fix this in the next patch release as the impl type doesn't expose any additional methods.
