### ISSUE TITLE
LinkStatusListener interface methods are not being called for Java bindings.

### ISSUE THREAD

**Issue by RaberShef** [dnp3/opendnp3#422]
Hello, I'm using OpenDNP3 3.1.1 and running a master application in java.
I implemented my own "MyMasterApplication" class which implements MasterApplication interface,
the only difference between the DefaultMasterApplication class and mine is that I added loggers to the onStateChange, onKeepAliveInitiated, onKeepAliveFailure and onKeepAliveSuccess methods which are methods of the LinkStatusListener interface.

When I connect to a substation, I can see the keep-alive messages being exchanged however I was not able to see any of the above methods being called. 

Can anyone confirm that these methods are being called correctly in Java?

Edit: It looks like the JNI files for LinkStatusListener are missing, maybe that is the cause?

**Comment by jadamcrain** [comment]
Opened a ticket here with root cause info:

https://github.com/dnp3/opendnp3/issues/423

This would be relatively simple to resolve.  Just need implement the missing `ILinkListener` listener in these 2 adapter classes.
