### ISSUE TITLE
[outstation] retrieving command requests from master

### ISSUE THREAD

**Issue by Sevendi** [dnp3/opendnp3#426]
Hi All,

Any body can help me to give some references or sample codes of how to retrieve the command requests that are sent by the master?

#ICommandHandler

Thank you!

**Comment by emgre** [comment]
There's documentation about the `ICommandHandler` in the [guide](https://dnp3.github.io/docs/guide/3.0.0/api/outstations#icommandhandler). The [`SimpleCommandHandler`](https://github.com/dnp3/opendnp3/blob/132f2fdb62ad9325efa8293fb122800ee2476aa2/cpp/lib/src/outstation/SimpleCommandHandler.cpp) is a good example.
