### ISSUE TITLE
Read TimeAndDate (Group 50 Variation 1) not supported

### ISSUE THREAD

**Issue by mosseedwin** [dnp3/opendnp3#427]
When I send Read TimeAndDate (Group 50 Variation 1) to the server, the response is Function not supported.

**Comment by emgre** [comment]
OpenDNP3 supports g50v1 only in a write request following a non-LAN time sync as described in section 10.3.3.1 of IEEE 1815-2012. Reading its value is currently not supported.

OpenDNP3 is currently feature freezed as we concentrate our efforts on our next generation libraries written in Rust. We will only be doing bug fixes on OpenDNP3. You can have a look at our new DNP3 library available here: https://stepfunc.io/products/libraries/dnp3/

We would be happy to merge a PR with this functionality if it meets our quality standard, has the necessary unit tests and exposes it to the C# and Java bindings.
