### ISSUE TITLE
Java build version 3.0.4 found on  https://repo1.maven.org/maven2/com/automatak out of date from release branch.

### ISSUE THREAD

**Issue by mtaylor-utilidata** [dnp3/opendnp3#431]
It appears that new methods have been added to the Java src has had updates since the dependencies were deployed to  https://repo1.maven.org/maven2/com/automatak last. Namely I ran into:

`java.lang.NoSuchMethodError: com/automatak/dnp3/OutstationApplication.onConfirmProcessed(ZJJJ)V `

Investigating I found the definition of OutstationApplication.class which as installed by maven from the public repo as follows:

```
public interface OutstationApplication extends LinkStatusListener {
    boolean supportsWriteAbsoluteTime();

    boolean writeAbsoluteTime(long var1);

    boolean supportsAssignClass();

    void recordClassAssignment(AssignClassType var1, PointClass var2, int var3, int var4);

    ApplicationIIN getApplicationIIN();

    RestartMode coldRestartSupport();

    RestartMode warmRestartSupport();

    int coldRestart();

    int warmRestart();

    DNPTime now();
}
```

Notably this is missing `onConfirmProcessed()` https://github.com/dnp3/opendnp3/blob/132f2fdb62ad9325efa8293fb122800ee2476aa2/java/bindings/src/main/java/com/automatak/dnp3/OutstationApplication.java#L100

For now I'm building from src and installing manually in our docker processes. I think a maven deploy (possibly with a version bump in the pom.xml) would resolve this issue.

**Comment by emgre** [comment]
As far as I remember, we've never published the bindings to Maven central. There are some old unsupported projects there, but not OpenDNP3. The 3.0.4 version that you are seeing probably comes from your local Maven repository, from the last time you ran `mvn install` on a local copy of OpenDNP3.

Our new rust-based DNP3 library is available on Maven with binaries for x64 Windows and Linux here: https://search.maven.org/artifact/io.stepfunc/dnp3 Its license requires a purchase for commercial purposes, but it's available for free for evaluation and non-commercial purposes. More details here: https://stepfunc.io/products/libraries/
