### ISSUE TITLE
Unable to bind server to the specified port: The requested address is not valid in its context

### ISSUE THREAD

**Issue by mack0196** [dnp3/opendnp3#433]
I am using opendnp3 v3.1.1 attempting to connect to a new generation controller installation using TLS.
Starting with the example in master-gprs-tls, I am getting this error with my IPEndpoint and TLSConfig
_"Unable to bind server to the specified port: The requested address is not valid in its context."_

This my first DNP3 experience and I don't have a lead from that error. Any suggestions\directions on how to investigate if the problem is on my end or the generation controller?

![image](https://user-images.githubusercontent.com/6463105/133516269-c15d6ff0-8aea-41de-ac55-65ac8fb3d4d7.png)

**Comment by emgre** [comment]
Can you show us what is the `IPEndpoint` you are trying to bind to?

**Comment by mack0196** [comment]
This was an IP filtering issue.
