### ISSUE TITLE
Add callback and/or poll support for network traffic usage

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#50]
For certain network types which charge per byte, it would be useful to have the dnp stack report its traffic usage as a function of async_read/write() calls.  Some mechanism to allow for real-time callback and scheduled polling of these values would be good.

**Comment by jadamcrain** [comment]
OK. It sounds like the right place to add the usage statistics would be in the PhysicalLayer base class.  Any proposal on what the interface would be? How can we add these such that the "counters" are generic.  For instance, we might want to track "crc failures" too.

**Comment by cverges** [comment]
Agreed, generic would be good.

The key components of the callback needed are:
- Bytes transferred
- Direction (transmitted/received)
- Error status

It sounds like an enum should be used to handle the error status, and we can just add to that enum as things are added to this interface.  The direction should be easy enough, but likely best as an enum for type-safety.

Thoughts?

**Comment by jadamcrain** [comment]
phys rx/tx now tracked along with open/close/fail counts
