### ISSUE TITLE
MasterAdapter.cpp - should be TotalMiliseconds

### ISSUE THREAD

**Issue by robrhce** [dnp3/opendnp3#52]
Should be TotalMilliseconds instead of Milliseconds

IMasterScan^ MasterAdapter::AddClassScan(int aClassMask, System::TimeSpan period, System::TimeSpan taskRetryPeriod)
{
        auto scan = mpMaster->AddClassScan(aClassMask, openpal::TimeDuration::Milliseconds(period.Milliseconds), openpal::TimeDuration::Milliseconds(taskRetryPeriod.Milliseconds));
        return gcnew MasterScanAdapter(scan);
}

**Comment by jadamcrain** [comment]
Thank you for submitting. I will be implementing this fix today.

**Comment by jadamcrain** [comment]
I've added a conversion to routine for all instances of TimeSpan -> TimeDuration.  A search revealed some other places where .Milliseconds was being used as well.
