### ISSUE TITLE
User callback to allow for pseudo-randomization of TCP retry attempts

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#54]
The TCP retry mechanism is currently set to a static period.  I'm encountering a problem right now where this causes a persistent deadlock due to a race condition in networking equipment.  What would fix it is if I had the ability to pseudo-randomize (like via a back-off timer) connection attempts.

Ideally, this mechanism should be exposed to the user application as a callback hook "tcpRetryWaitBeforeReconnecting()" or something.

**Comment by jadamcrain** [comment]
I think we decided that the exponential backoff feature would be fine for this, yes? I need to expose the configuration parameters for this.

**Comment by cverges** [comment]
I think you suggested an exponential backoff, but I would still like the ability to have a user-provided callback to allow for full ability to tweak things.  Such flexibility would be expected out of the reference implementation!

For example, it could be that based on changing network conditions, we choose to do things differently with re-attempting: sometimes more aggressive, sometimes more timid.  But a raw backoff feature wouldn't be able to dynamically respond like this.

**Comment by jadamcrain** [comment]
I could provide an inject-able interface that gives you the option override the retry. The default would be a singleton that doubles up to some reasonable limit like 5 minutes.

**Comment by jadamcrain** [comment]
Oh, and where are you these days? Don't see you on gtalk :)

**Comment by cverges** [comment]
Your proposal sounds ideal!

Stupid IM client.  Let me kick it in the rear.

**Comment by jadamcrain** [comment]
OK, in C++ you can optionally inject an "IOpenRetryStrategy":

https://github.com/automatak/dnp3/commit/19ff2abef3cd01daada1de96130d926c69aa0864

This defaults to exponential backoff.

I'll need someone from Sentient to push this up though the Java bindings if you want this in the next release. I'm absolutely swamped and already behind schedule.
