### ISSUE TITLE
"Address incompatible with the requested protocol" error when creating a new boost socket

### ISSUE THREAD

**Issue by HVDCwilliams** [dnp3/opendnp3#55]
Hello,
I am try in to add another socket to my program that is already running openDNP3. however when I create another boost connection acceptor, the openDNP3 errors saying "An address incompatible with the requested protocol was used" is it possible to create another acceptor while running the openDNP3? if so how can it be done?
Thanks
DW

**Comment by jadamcrain** [comment]
Hi,

Post the question to the Google group please:

http://groups.google.com/group/automatak-dnp3

thanks,
Adam
