### ISSUE TITLE
Measurement timestamps should have a way to indicate they are not present in the actual DNP update

### ISSUE THREAD

**Issue by cverges** [dnp3/opendnp3#56]
Scenario:
- Outstation has a Class 1 Analog or Binary Input point with a timestamp (not 1970-01-01 00:00:00.000) associated
- Application registers a master stack to some outstation
- Stack starts to come up, issuing "Read Class 0" (integrity scan) then "Read Class 1,2,3" (exception scan)
- Stack passes the results of the integrity scan to the application
- Application parses the results, but sees the timestamp set as "1970-01-01 00:00:00.000" as a result of no timestamp being provided in the static object type
- Stack passes the results of the exception scan to the application
- Application sees the timestamp set properly now

There is no way for the application to distinguish between a false timestamp (1970-01-01 00:00:00.000) that was injected as a result of the integrity poll and a real timestamp (which _could_, though unlikely, be set to the same) as a result of an exception scan.

**Comment by jadamcrain** [comment]
Been on the mental to-do list for a while now.

**Comment by cverges** [comment]
Generally, it could be also useful to indicate the source of the update (integrity, exception, unsol, etc)

**Comment by jadamcrain** [comment]
This is resolved in 2.0.x. All measurements have a "IsTimeValid" method:

https://github.com/automatak/dnp3/blob/2.0.x/cpp/opendnp3/src/opendnp3/app/BaseMeasurementTypes.h#L39

Also, the master can also tell you if the events being received are events or static values tooL

https://github.com/automatak/dnp3/blob/2.0.x/cpp/opendnp3/src/opendnp3/master/ISOEHandler.h

SOE stands for "sequence of events"
