### ISSUE TITLE
Read requests are ignored while waiting for an unsolicited confirmation

### ISSUE THREAD

**Issue by hungle** [dnp3/opendnp3#57]
Our customer is finding that on start-up, the DNP stack does not respond to any read request until a confirmation is first sent. I dug into it and the stack appears to be expecting a confirmation on start-up because of the start-up unsolicited message requirement. While the start-up unsolicited message is appropriate, I believe that according to the standard, if a read request comes in while the outstation is waiting for unsolicited response confirmation that it should at some point times out, abort the unsolicited series and respond to the read request instead. Per rule 16 Section 4.6.6 of the standard:

If the outstation receives a read request of any kind while waiting for a confirmation to an unsolicited response, it shall defer building a response until either
    1) The unsolicited response confirmation is received. The outstation shall then
        i) Immediately clear the confirmed event data from its event buffer(s) according to Rule 11.
        ii) Respond to the deferred read request as though it had just been received.
    2) Timeout occurs waiting for the unsolicited confirmation. At this time, the outstation shall not send a retry unsolicited response; instead it
        i) Shall terminate the current unsolicited response series17, assume the confirmation is not forthcoming, and make the events available to be reported in a subsequent solicited response or a subsequent original unsolicited response.
        ii) Respond to the deferred read request as though it had just been received and wait for confirmation to that read response if confirmation is required.
        iii) Thereafter, may formulate a new original unsolicited response for any remaining events that are permitted18 to be transmitted in an unsolicited response.

**Comment by jadamcrain** [comment]
Will investigate for 2.0.0-RC1

**Comment by jadamcrain** [comment]
Even though the 3rd party master should be confirming unsolicited packets, careful investigation revealed a non-conformance in opendnp3 as well.  When a READ is received while waiting for a confirm, any further retries should be canceled. This has been patched on the 1.1.x branch:

https://github.com/automatak/dnp3/commit/485b3716737e839bbf9ef5db52e2d9fc049244a0

A conformance test has been added to the external test harness to ensure this makes into 2.0.x with the new state machines as well.

**Comment by z-abdellahi** [comment]
by which tool did u send read request in dnp3???
