### ISSUE TITLE
2.0.x - CommandResponse.Result always NO_COMMS in 2.0.x branch

### ISSUE THREAD

**Issue by robrhce** [dnp3/opendnp3#58]
CommandResponse.Result appears to be always NO_COMMS in the 2.0.x branch

Looks like its because the Ctor initialiser uses a fixed value instead of a parameter and the CommandResponse::OK method is never called by CommandTask

CommandResponse::CommandResponse(CommandResult aResult, CommandStatus aStatus) : 
    mResult(CommandResult::NO_COMMS), 
    mStatus(aStatus) 
{}

Should this just be:

```
mResult(aResult), 
mStatus(aStatus) 
```

?

Not sure if this issue persists in the 'parser' branch or not

**Comment by jadamcrain** [comment]
Will investigate the week of the 20th. Thanks for the bug report and monitoring of 2.0.x development branch.

**Comment by jadamcrain** [comment]
Thanks for the report. Resolved here:
https://github.com/automatak/dnp3/commit/4bdbb99129871108c82ec1f7e8df758b2f1fa240
