### ISSUE TITLE
Using --enable-opendnp3nomaster causes error

### ISSUE THREAD

**Issue by bsmucker** [dnp3/opendnp3#59]
When I configure using the --enable-opendnp3nomaster switch, then make, I get the following error:

In file included from cpp/src/opendnp3/DNP3Channel.cpp:23:0:
cpp/src/opendnp3/DNP3Channel.h:60:118: error: 'IMonotonicTimeSource' has not been declared

This is in 1.1 branch of things.

Not sure what is going on.

**Comment by jadamcrain** [comment]
I don't believe this feature has been consistently maintained.  It will likely be removed in 2.0.x unless there is a champion that wants to maintain all these optional DEFINES.

**Comment by jadamcrain** [comment]
Nobody has volunteered to maintain these macros or expressed much interest. They will be removed in 2.0.x
