### ISSUE TITLE
Add link-layer keep alive using REQUEST_LINK_STATES as per specificaiton

### ISSUE THREAD

**Issue by jadamcrain** [dnp3/opendnp3#63]

**Comment by atmurray** [comment]
Thoughts on the following?
https://github.com/atmurray/dnp3/commit/c1a535d9720ec26458c8c1cb8a82a607e653ee2d
Next step is to create unit tests.

**Comment by jadamcrain** [comment]
I'll pull it down and have a look.

In a quick scan I didn't see a way to reset the channel? I guess we need a call to allow the higher layer to force a channel close.

**Comment by atmurray** [comment]
I reused the OnTimeout function to retry request link status up to
RetryRemaining.
On receipt of link status, PLLS transitions to SecReset.
On failure, PLLS transitions to SecNotReset.

This what you mean?

The KeepAlive timer is reset every time a valid link layer message is
received.
The time is reset by cancelling the timer and creating a new one.
Whilst I'm not sure of the complexity of this approach, it should be
equivalent to the existing transmit timeout complexity.

**Comment by jadamcrain** [comment]
Shouldn't transition to SecReset.  That state is reserved for using link-layer confirms. It should transition to whatever state it was in when the link status interval expired. That state might be SecReset or SecNotReset.

The way the timer is implemented is just fine. I was more asking "what do we do when the remote side doesn't respond to X link status queries?". The spec says we need to actually close the socket/chanel/whatever. To do that, we're going to need to need to add a Close() method to the ILinkRouter interface:

https://github.com/automatak/dnp3/blob/2.0.x/cpp/libs/opendnp3/src/opendnp3/link/ILinkRouter.h

In most situation, just writing to the dead socket should be enough to trigger a close, but I think we need this anyway.

**Comment by atmurray** [comment]
Ah got it.
Reading the standard, failed link resets close the channel too?
Also, it seems to say that its up the implementation to decide on the
implications of confirmed user data failure.

Presumably sending a close to ILinkRouter will only close the physical
layer (i.e. TCP socket) if there are no other open link layers (in the case
of multidrop)?

**Comment by jadamcrain** [comment]
We'll have to make this configurable, including have no link status behavior whatsoever. It only makes sense in the context of TCP, and in that case multi-drop isn't often used (although I know you guys are). If the behavior is configurable, I tihnk we're in good shape.

**Comment by jadamcrain** [comment]
Another note:

If trakcing the "sec reset" state is too complex, you could consider moving this to a flag instead of represented as a class. Coupled states are no fun. I may not have done this the best way possible when it was originally implemented. The link-layer state machine and below is some of the oldest code in opendnp3.

**Comment by neilstephens** [comment]
We addressed the issue of making the response to a failed keepalive configurable, by using the new link layer status callback interface. This way, the listener can decide what response is appropriate, like closing the channel, disabling the stack, waiting to see if it comes good again, etc.

**Comment by jadamcrain** [comment]
I decided to go a slightly different direction w/ the listener and heartbeats:

https://github.com/automatak/dnp3/blob/2.0.x/cpp/libs/src/opendnp3/link/ILinkListener.h

All of the callbacks are now on a single interface, and IMasterApplication / IOutstationApplication inherit from ILinkListener,

I did a lot of refactoring to the the link-layer state machine. I realized you also said there was a conformance issue in the state machine. Would you mind writing a unit test to demonstrate it?

**Comment by neilstephens** [comment]
Yep, no problem. I think we might have already written a test, but it's on
the laptop at work. I'll set a reminder to have a look.

FYI, I think the conformance issue you're referring to was the missing
state transitions from wait states back to idle when an unexpected function
code is received. It's one of the last commits I made on my fork if you
wanted to take a look.

Cheers,
Neil.

**Comment by jadamcrain** [comment]
I am going to close this tickets.

I have support in 2.1.0-RC1 for this with callbacks being to sent to ILinkListener (IMasterApplication / IOutstationApplication inherit form this).

Take 2.1.0-RC1 for a spin when you have time. We'll do a month long release candidate process since there have been so many changes.
