### ISSUE TITLE
Add ability to perform basic READ commands

### ISSUE THREAD

**Issue by atmurray** [dnp3/opendnp3#65]
Some basic outstations only support reading objects using read all/range commands.
Suggested enhancement is to implement a demand and period read function (eg AddReadScan).

**Comment by jadamcrain** [comment]
Yes. I envision something like:

IScan\* pScan = pMaster->AddReadRangeInt16(GroupVarEnum, start, end);

**Comment by atmurray** [comment]
Exactly, once again I'm happy to look into this and make some proposals.

**Comment by jadamcrain** [comment]
Implemented in 2.0.x.
