### ISSUE TITLE
2.0.x make install does not install headers

### ISSUE THREAD

**Issue by tarm** [dnp3/opendnp3#69]
In the 2.0.x branch, doing a make install does not install the headers anymore.  The headers are installed in the 1.1.x branch.  Looks like commit 6335e666 removed them from Makefile.am.

**Comment by jadamcrain** [comment]
Thanks for the placeholder. We used to install a subset of headers, but it becamse evident that it was impossible to predict the part of the library people wanted to use (link layer,etc). I believe that we should now just install all headers.

**Comment by cverges** [comment]
Headers are cheap!

**Comment by jadamcrain** [comment]
The secauth branch is migrating to cmake. We'll have a better way of installing headers without having to name each one when that gets merged into 2.0.x.

**Comment by jadamcrain** [comment]
The 2.0.x cmake toolchain now installs headers. The 2.0.2 release will include this functionality.
