### ISSUE TITLE
PostLambda in IExecutor

### ISSUE THREAD

**Issue by gitroberto64** [dnp3/opendnp3#71]
Compilation in Linux:
cpp/asiodnp3/src/asiodnp3/DNP3Channel.cpp:67:69: error: no matching function for call to 'openpal::IExecutor::PostLambda(asiodnp3::DNP3Channel::GetChannelStatistics()::<lambda()>)'

It seems that it should be:
    template <class Lambda>
    void PostLambda(const Lambda& lambda)

**Comment by jadamcrain** [comment]
Only doing periodic spot-checks on Linux.  The last milestone release had a stable linux build. This will get cleaned up during the next spot check with GCC/Clang.
