### ISSUE TITLE
Support for discontiguous indexes

### ISSUE THREAD

**Issue by atmurray** [dnp3/opendnp3#79]
Add support for non-contiguous ranges of indexes so that sparse points databases can be efficiently implemented.

**Comment by atmurray** [comment]
First commit of support branched from 2.0.x RC-2 here:
https://github.com/atmurray/dnp3/compare/discontiguous

**Comment by jadamcrain** [comment]
Thanks Alan. I will check this out and get it merged.

-AC

**Comment by atmurray** [comment]
OK great, you'll likely have questions so I started this discussion: https://groups.google.com/forum/#!topic/automatak-dnp3/UUTcTa82Xz0

**Comment by jadamcrain** [comment]
Support was integrated in 2.0.1-RC1
