### ISSUE TITLE
Question about objects 110 and 111

### ISSUE THREAD

**Issue by antiquechrono** [dnp3/opendnp3#82]
I'm at a loss as for how to poll objects 110 and 111. The only way I can see how to do this is via a RangeScan, but no matter what I pick the device keeps sending back a "parameters invalid or out of range" status. I'm having a hard time figuring out if I'm doing something wrong, the library doesn't support these objects, or if something is wrong with the device I'm talking to. I'm using the .net interface if that makes a difference. Thanks for your time.

**Comment by jadamcrain** [comment]
Hey, we use the google group's mailing list and forum for general questions like this:

http://groups.google.com/group/automatak-dnp3

Just join and re-post the question. Will be happy to help.
