### ISSUE TITLE
No rule to make target 'cpp/libsopendnp3/src/opendnp3/link/LinkLayerRouter.cpp', needed by `cpp/libs/opendnp3/src/opendnp3/link/libopendnp3_la-LinkLayerRouter.lo'.

### ISSUE THREAD

**Issue by jpmec** [dnp3/opendnp3#86]
I have cloned the repo and am trying to make.

I get the following error:

make: **\* No rule to make target `cpp/libs/opendnp3/src/opendnp3/link/LinkLayerRouter.cpp', needed by`cpp/libs/opendnp3/src/opendnp3/link/libopendnp3_la-LinkLayerRouter.lo'.  Stop.

I am using OSX 10.9.4

```
Josh@macbookpro~/Projects/opendnp3$ clang --version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
```

I have cloned the asio git repo and set my environment variable correctly (I think).
I ran:

```
autoreconf -i -f
./configure
make
```

**Comment by jadamcrain** [comment]
You're doing everything correctly, we just haven't updated the makefile on the tip of master as most development is done in Visual Studio.  If you want something stable try 2.0.0-RC2 tag. Hoping to have 2.0.0-RC3 out today or tomorrow.

**Comment by jadamcrain** [comment]
Fixed in:
https://github.com/automatak/dnp3/commit/834df22545ba79a9d66a27867d456b8973feddde

**Comment by jpmec** [comment]
Hi @jadamcrain, thank you so much for your fast response!  This seems to have fixed the problem I was having.  I am now having a similar issue for DynamicallyAllocatedDatabase.cpp

```
make: *** No rule to make target `cpp/libs/asiodnp3/src/asiodnp3/DynamicallyAllocatedDatabase.cpp', needed by `cpp/libs/asiodnp3/src/asiodnp3/libasiodnp3_la-DynamicallyAllocatedDatabase.lo'
```

Do you want me to make another issue for this?  I will see if I can fix this myself based on your previous edits.  But as far as a pull request, maybe it is better if you fix and I will pull your changes?  I am still new to this project.  (BTW, I am very excited about finding this.  I am just now starting with DNP3 and hopefully will be able to contribute something meaningful to this project in the future)

**Comment by jadamcrain** [comment]
Sorry, I fixed it in the commit above, but broke it again as I was actively working from Visual Studio today.

I would just checkout from the 2.0.0-RC2 tag for now. I hope to have all of this stabilized tomorrow sometime.

-AC

**Comment by jadamcrain** [comment]
Also, highly recommend you join mailing list:

http://groups.google.com/group/automatak-dnp3

**Comment by jpmec** [comment]
Cool, will do.  Thanks!
