### ISSUE TITLE
2.0.0-RC2 ld: unknown option: --no-as-needed

### ISSUE THREAD

**Issue by jpmec** [dnp3/opendnp3#87]
I get this error when trying to make the 2.0.0-RC2 tag.

A quick fix is to remove this from Makefile.am, then run ./configure again

OSX 10.9.4

```
Josh@macbookpro~/Projects/opendnp3$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
```

**Comment by jadamcrain** [comment]
OK. I think was needed due to a gcc bug. I can track down if this flag is
still needed or not.

Have you done a 'make check' and run the two test suites?

**Comment by jpmec** [comment]
@jadamcrain, I ran 'make check' but am still trying to figure out how to run the two test suites.  I will look into this issue tonight.  I use OSX at home.

**Comment by jpmec** [comment]
@jadamcrain, just found the two tests 'dnp3test' and 'openpaltest' in the root of the repo after doing 'make check'.  Ran them both and all tests passed.

**Comment by jadamcrain** [comment]
Tip of 2.0.x only uses this work-around for the appropriate compiler/versions.
