### ISSUE TITLE
ASIO_HOME directory set to two different values for OSX versus Windows

### ISSUE THREAD

**Issue by jpmec** [dnp3/opendnp3#88]
When using autotools and make on OSX, the '/include' portion of the path is added by the configuration tools.  On Windows, with Visual Studio 2013, ASIO_HOME needs the '/include' portion of the path in the environment variable.

**Comment by jadamcrain** [comment]
@jpmec. Good catch. These two should be consistent. Documentation says:

http://dnp3.github.io/doc/2.0.x/building/prerequisites.html

Therefore, I will remove the '/include' portion from Makefile.am.

**Comment by jadamcrain** [comment]
Fixed in 7e0c51da40c2860fa30534a8e0b6d9373301769b
