### ISSUE TITLE
Examples and Simulator require Visual C++ Redistributable Packages to be installed on target Windows computers

### ISSUE THREAD

**Issue by jpmec** [dnp3/opendnp3#89]
This is probably just a note for the documentation, but I stumbled on this point, so I thought I'd leave a breadcrumb for other newbies.  Perhaps something about this can be added to the documentation?

After you build the opendnp3.sln with Visual Studio 2013, if you plan on running the programs on another computer, other than the one you built the software on, you will have to install the Visual C++ Redistributable Packages for Visual Studio 2013.

I mention this because the error that the SimulatorApplication.exe gives is there was a problem with the DNP3CLRAdapter.dll.  The outstationdemo states that it cannot find the missing msvcp120.dll, so that's what clued me in to fixing the problem.

**Comment by jadamcrain** [comment]
Documentations for 2.0.x is incomplete / incorrect in a number of regards. It's going to require a line by line pass.

This is definitely an area where I'm looking for volunteers to help out:

https://github.com/automatak/dnp3-guide

**Comment by jpmec** [comment]
Cool, I'd be happy to help!  BTW, the Visual Studio 2013 solution compiled with no problems once I had my environment setup right.  I had to install the Windows 8.1 SDK.  I have both the outstationdemo.exe and SimulatiorApplication.exe running on two machines (development machine and target user machine).  I'm definitely excited about using them both!
