### ISSUE TITLE
Feature: Add command line options to outstationdemo

### ISSUE THREAD

**Issue by jpmec** [dnp3/opendnp3#90]
I would like to be able to specify command line options for the outstationdemo.  For example, I would like to be able to configure the following lines:

```
auto pChannel= manager.AddTCPServer("server", FILTERS, TimeDuration::Seconds(5), TimeDuration::Seconds(5), "0.0.0.0", 20000);   

stackConfig.outstation.params.allowUnsolicited = true;

stackConfig.link.LocalAddr = 10;

stackConfig.link.RemoteAddr = 1;
```

I'd be happy to implement this feature.  However, I'd like some feedback from @jadamcrain or other project contributors, if there are any preferences on the implementation.  Thanks!

**Comment by jpmec** [comment]
Created a simple implementation here:

https://github.com/jpmec/dnp3/tree/2.0.x-feature/outstationdemo-command-line-options

**Comment by jadamcrain** [comment]
Sure. Are you willing to add the exact same features to the .NET CLI demos as well for consistency?

**Comment by jpmec** [comment]
@jadamcrain, sure?  I think I can do this.  I am not as familiar with .NET, but I can probably figure it out.  I'll put the changes in my feature branch and let you know when I have that part done.

Also, as a side note, it seems like the "better" way to do this in the long term is "config serializer objects".  For instance, an OutstationStackConfigJSONSerializer that could read and write attributes of the OutstationStackConfig to and from a stream of JSON data.  Of course, this choice would mean a lot more effort and dependencies.  Is there any preferences for configuration file formats, and libraries?  

BTW, I'm not a big fan of XML, but I know that .NET and XML get along quite well.  My personal preference would be JSON?  Are there any configuration file formats that are widely used in the dnp3 world?

**Comment by jadamcrain** [comment]
DNP3 World? I wouldn't take anything that gets done in SCADA as "best practices". LoL.

I would prefer to keep the C++ free of any additional dependencies besides ASIO. It's meant to be lean especially the opendnp3/openpal sub-libraries that can run on microcontrollers.

The config in C# is XMLSerializable, e.g.:
https://github.com/automatak/dnp3/blob/2.0.x/dotnet/bindings/CLRInterface/ClassField.cs#L63

The entire config strucutre for MasterStackConfig & OutstationStackConfig follows XML serialization rules. I don't really like XML either, but it's what some of my customers have asked for.

**Comment by jadamcrain** [comment]
Hey Josh,

Any progress on adding command line options? If so, I'll wait, if not I am going to close the ticket. Let me know.

-Adam
