### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [dnp3/opendnp3#91]
I would like to point out that identifiers like "[`__OPENDNP3_ROUTE_H_`](https://github.com/automatak/dnp3/blob/c03c3c6b72c4f09df38d8154e78d1d4e43ff5d1d/cpp/libs/opendnp3/src/opendnp3/Route.h#L21)" and "[`__I_MASTER_H_`](https://github.com/automatak/dnp3/blob/a87589f04f4da46e66b540c0f351bd1cf90e712a/cpp/libs/asiodnp3/src/asiodnp3/IMaster.h#L21)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jadamcrain** [comment]
Looks like Google & BOOST say the project prefix convention is OK:
http://stackoverflow.com/questions/4867559/naming-include-guards

Item above would be:
OPENDNP3_ROUTE_H
I_MASTER_H

**Comment by elfring** [comment]
How do you think about to make [your include guards](http://en.wikipedia.org/wiki/Include_guard#Difficulties) not only [standard-compliant](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797) but also really unique by appending [a kind of UUID](http://en.wikipedia.org/wiki/Universally_unique_identifier)?
- Can [an approach from an attachment](https://bugreports.qt-project.org/browse/QTBUG-5004) help?
- Is [another guide line](http://pyne.io/devsguide/style_guide.html#include-guards) interesting?
- Do you find the functionality "Search and replace in files" by [the tool "KDevelop 4.6"](https://www.kdevelop.org/) useful?

**Comment by jadamcrain** [comment]
BTW, bots that auto-file tickets are pretty obnoxious. Thanks, but no thanks.
